### ISSUE TITLE
Link of record to FPT

### ISSUE THREAD

**Issue by nosamttam** [ekonbenefits/dotnetdbf#12]
Greetings -
Is there a pointer in the DBF record that points to a specific location in the FPT where the associated Memo Field is located, or does it work the other way around - the MEMO FPT points the record in the DBF?

**Comment by jbtule** [comment]
Only support DBT Memo files. But the block pointer that references the location inside a DBT file is in the DBF.

**Comment by jbtule** [comment]
consolidating this with issue #18
