### ISSUE TITLE
Add db type T

### ISSUE THREAD

**Issue by monty241** [ekonbenefits/dotnetdbf#27]
The current supported types in NativeDbType are: +,@,B,C,D,F,G,I,L,M,N,O.

However, sources such as [http://www.dbfree.org/webdocs/1-documentation/b-dbf_header_specifications.htm](http://www.dbfree.org/webdocs/1-documentation/b-dbf_header_specifications.htm) and [https://www.dbf2002.com/dbf-file-format.html](https://www.dbf2002.com/dbf-file-format.html) report more types:

- C: Character (binary)
- P: Picture
- T: DateTime
- V: Varchar type (Visual Foxpro)
- Y: Currency

In the field I have seen T occurring.

Maybe these five types can be added.

**Comment by jbtule** [comment]
I believe those are like fox pro types, I don't know what all needs to be done to actually support outside of DBase III dbfs.

**Comment by monty241** [comment]
We just do reading on the files. For now, we have hard-coded the logic ourselves, since we translate the data types in data types of Invantive SQL. 

As a first step it might be an option to extend DBFReader with some file header properties not yet present:
* File type
* Last update
* Position of first data record 
* Length of 1 record
* For each flag one.
* Code page mark.
* Path to backlink.

Dito for fields:
* field flags like nullable
* next value
* step size

I found those missing during analyzing various cases, especially since .NET Standard and Framework versions have small differences.

Would you be open to PR?

**Comment by jbtule** [comment]
I'd be open to a pull request, but would only accept as long as it's done it a backwards compatible way to DBF III, which is what we use it for.

**Comment by monty241** [comment]
OK. DBF 3 is back uni time for me. I suspect that coding according to http://www.dbfree.org/webdocs/1-documentation/b-dbf_header_specifications.htm would ensure that.

But to be sure: are there some DBF 3 files in the tests?

**Comment by monty241** [comment]
Ping to -4061 and -4062.

**Comment by jbtule** [comment]
closing in favor of just returning byte arrays for unknown types  ref #29

**Comment by IgorShir77** [comment]
Hello! Can't save "DateTime" value to dbf file for vfp. Can you show me an example, please.
