### ISSUE TITLE
Include DataMemoLoc support in .NET Standard build

### ISSUE THREAD

**Issue by monty241** [ekonbenefits/dotnetdbf#28]
DataMemoLoc on DBFReader is only support on .NET Framework, not on .NET Standard.

Support on .NET Standard makes use of DBF on Mac, Linux, iOS and Android easier.

Workaround is to use:
```
#if (!NETSTANDARD2_0)
                        {
                            DataMemoLoc = Path.ChangeExtension(databaseFilePath, this.DatabaseMemoFileNameExtension)
                        }
#endif

```

**Comment by jbtule** [comment]
DataMemo (Stream) should work on .netstandard and .netframework.  I think this was an old PCL issue though, they were getting rid of all the filesystem apis, so maybe will change it back for .netstandard.

**Comment by jbtule** [comment]
removed .netstandard 1.3, and then was easy to remove all ifdefs.

completed in 16ac340e9f522f35514ad4920d9ded17d7e7164f

**Comment by monty241** [comment]
great! Makes it possible to use also on iPhone or Mac with no major constraints
