### ISSUE TITLE
Error on inserting a chinese record

### ISSUE THREAD

**Issue by jbtule** [ekonbenefits/dotnetdbf#4]
Reported by bobbychencj, Aug 24, 2011

What steps will reproduce the problem?
1. Use DBFWriter object and set CharEncoding is "GB2312"
2. Use chinese character create a record object array.
3. Use DBFWriter insert this record into dbf file.
4. Use DBFReader read last record.

What is the expected output? What do you see instead?

I expected a record like this: "5","自报数","一二三四五六七"
but actual value like this:    "5","自?",","一二三?"

What version of the product are you using? On what operating system?

I user ver 3.0.3 (.net 3.5 DLL) to run.
My OS is Win7 x86 and Win7 x64.

Please provide any additional information below.

This DBF file is "FoxBase+/dBase III Plus,no meno".
I Update load this DBF file,which has been insert a record.

this DBF file field structure is:

Field Name      Type        Size
  LB         Character       1
  BH         Character       10
  MC         Character       30

By the way If you can't use chinese to test. Email me,I will try to help you.

See attachment in original issue:

https://code.google.com/p/dotnetdbf/issues/detail?id=6

**Comment by wuchang** [comment]
![qq 20150428000147](https://cloud.githubusercontent.com/assets/137900/7351774/e6bf1366-ed39-11e4-8a0e-9b1a3fcbc8e6.png)

**Comment by wuchang** [comment]
用gb2312编码

![Uploading QQ截图20150428000441.png . . .]()

**Comment by wuchang** [comment]
![Uploading QQ截图20150428000441.png . . .]()

**Comment by leixu2txtek** [comment]
any ideas plz ?

**Comment by jbtule** [comment]
@leixu2txtek  I tested the following code in linqpad, and the original issue from 2011 isn't occurring. Can you let me know what your issue is? Thanks.

```
var orig = "一二三四五六七";

using (var stream = new MemoryStream()){
	var writer = new DBFWriter();
	writer.Fields = new[] { new DBFField("F1", NativeDbType.Char, 100) };
	writer.AddRecord(orig);
	writer.Write(stream);
	stream.Position = 0;
	var reader = new DBFReader(stream);
	var result = reader.NextRecord();
	(result[0].ToString() == orig).Dump();
}// Dump said true
```

**Comment by leixu2txtek** [comment]
@jbtule Sorry, I only saw the news after a long time :).

I have resolved this promble with add register encoding by 

`` c#
            //注册 GB2312
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
``
