### ISSUE TITLE
Zeros erroneously being written as empty with NativeDbType.Numeric

### ISSUE THREAD

**Issue by blovell33** [ekonbenefits/dotnetdbf#9]
The following outputs a DBF file that should should have 0 for code in the first record, but instead is empty.

``` cs
using (var writer = new DBFWriter(dbf.Create())) {
  writer.Fields = new[] {
    new DBFField("code", NativeDbType.Numeric, 10, 0),
    new DBFField("desc", NativeDbType.Char, 100),
    new DBFField("abbr", NativeDbType.Char, 4)
  };

  writer.WriteRecord(0, "Unknown", null);
  writer.WriteRecord(1, "Yes", null);
  writer.WriteRecord(2, "No", null);
}
```

In Util.cs, inside of of the NumericFormating method, the following code is ran using the calculated format of "##########":

``` cs
return
  textPadding(
    doubleNum.ToString(format.ToString(), NumberFormatInfo.InvariantInfo),
    charEncoding,
    fieldLength,
    ALIGN_RIGHT);
```

When doubleNum is 0...

``` cs
0.ToString("##########", NumberFormatInfo.InvariantInfo)
```

...yields an empty string, however, writing 0 to the record is the desired behavior and having the format calculate as "#########0" would solve this.

**Comment by mbuceta** [comment]
This change seems It isn't in the last nuget package. Version 3.1.0.
Could you update the package ? Thank you very much.
